#!/bin/bash
# Family Dashboard - Daily Sync Script
# Run this via cron every morning to sync calendar, handball schedules, and commit changes

set -e

DASHBOARD_DIR="/Users/joao/.openclaw/workspace/projects/family-dashboard"
LOG_FILE="/tmp/family-dashboard-sync.log"
DATE=$(date +%Y-%m-%d)

echo "[$DATE] Starting Family Dashboard sync..." >> "$LOG_FILE"

cd "$DASHBOARD_DIR"

# Check if there are changes to commit
if [ -n "$(git status --porcelain)" ]; then
    echo "[$DATE] Changes detected, committing..." >> "$LOG_FILE"
    
    git add data/
    git commit -m "🤖 Daily sync: $DATE

- Auto-synced calendar events
- Updated handball schedules  
- Refreshed activity instances

Generated by Family Dashboard daily cron"
    
    git push origin main
    
    # Trigger GitHub Pages rebuild
    echo "[$DATE] Triggered GitHub Pages rebuild" >> "$LOG_FILE"
else
    echo "[$DATE] No changes to commit" >> "$LOG_FILE"
fi

# Run data ingestion (to be implemented)
# node dist/scripts/ingest.js

echo "[$DATE] Sync complete" >> "$LOG_FILE"
